/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/neon.glb 
*/

import * as THREE from "three";
import React, { useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations, PerspectiveCamera } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model({ scroll, ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/neon.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => void (actions["Animation"].play().paused = true), []);
  // useEffect(() => {
  //   if (hovered)
  //     group.current.getObjectByName(hovered).material.color.set("white");
  //   document.body.style.cursor = hovered ? "pointer" : "auto";
  // }, [hovered]);

  console.log("actions", actions);
  console.log("animations", animations);
  useFrame((state) => {
    actions["Animation"].time = THREE.MathUtils.lerp(
      actions["Animation"].time,
      actions["Animation"].getClip().duration * scroll.current,
      0.05
    );
    // group.current.children[0].children.forEach((child, index) => {
    //   child.material.color.lerp(
    //     color.set(hovered === child.name ? "tomato" : "#202020"),
    //     hovered ? 0.1 : 0.05
    //   );
    //   const et = state.clock.elapsedTime;
    //   child.position.y = Math.sin((et + index * 2000) / 2) * 1;
    //   child.rotation.x = Math.sin((et + index * 2000) / 3) / 10;
    //   child.rotation.y = Math.cos((et + index * 2000) / 2) / 10;
    //   child.rotation.z = Math.sin((et + index * 2000) / 3) / 10;
    // });
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Area"
          position={[8.074, 4.794, -1.616]}
          rotation={[-Math.PI / 2, 1.309, 0]}
        />
        <group
          name="Area001"
          position={[-19.249, 4.384, -7.271]}
          rotation={[-1.686, 0, 0]}
        />
        <group
          name="Area002"
          position={[-24.725, 4.384, -7.271]}
          rotation={[-1.686, 0, 0]}
        />
        <group
          name="Area003"
          position={[-13.81, 4.384, -7.271]}
          rotation={[-1.686, 0, 0]}
        />
        <group
          name="Area004"
          position={[-8.407, 4.384, -7.271]}
          rotation={[-1.686, 0, 0]}
        />
        <group
          name="Area005"
          position={[0.337, 3.213, 0.095]}
          rotation={[-Math.PI / 2, 0.226, 0]}
        />
        <group
          name="Area006"
          position={[0.337, 3.213, -1.902]}
          rotation={[-Math.PI / 2, 0.226, 0]}
        />
        <group
          name="Area007"
          position={[-0.944, 3.515, 0.095]}
          rotation={[-Math.PI / 2, 0.226, 0]}
        />
        <group
          name="Area008"
          position={[-0.944, 3.515, -1.902]}
          rotation={[-Math.PI / 2, 0.226, 0]}
        />
        <group
          name="Area009"
          position={[-2.226, 3.812, 0.095]}
          rotation={[-Math.PI / 2, 0.226, 0]}
        />
        <group
          name="Area010"
          position={[-2.226, 3.812, -1.902]}
          rotation={[-Math.PI / 2, 0.226, 0]}
        />
        <group
          name="Area011"
          position={[5.733, 3.801, 0.095]}
          rotation={[-Math.PI / 2, -0.228, 0]}
        />
        <group
          name="Area012"
          position={[5.733, 3.801, -1.902]}
          rotation={[-Math.PI / 2, -0.228, 0]}
        />
        <group
          name="Area013"
          position={[4.449, 3.51, 0.095]}
          rotation={[-Math.PI / 2, -0.228, 0]}
        />
        <group
          name="Area014"
          position={[4.449, 3.51, -1.902]}
          rotation={[-Math.PI / 2, -0.228, 0]}
        />
        <group
          name="Area015"
          position={[3.167, 3.216, 0.095]}
          rotation={[-Math.PI / 2, -0.228, 0]}
        />
        <group
          name="Area016"
          position={[3.167, 3.216, -1.902]}
          rotation={[-Math.PI / 2, -0.228, 0]}
        />
        <group
          name="Area017"
          position={[1.754, 3.442, 2.461]}
          rotation={[-1.368, 0, -Math.PI / 2]}
        />
        <group
          name="Area018"
          position={[-4.573, 4.794, -1.616]}
          rotation={[-Math.PI / 2, -1.309, Math.PI]}
        />
        <PerspectiveCamera
          name="Camera_ferma"
          makeDefault
          far={1000}
          near={0.1}
          fov={44.096}
          position={[10.169, 1.7, 14.377]}
          rotation={[0, 0.598, 0]}
        />
        <pointLight
          name="Point"
          intensity={1087.028}
          decay={2}
          position={[6.364, 1.77, 0.864]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <pointLight
          name="Point001"
          intensity={1087.028}
          decay={2}
          position={[6.234, 1.77, -2.796]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <pointLight
          name="Point002"
          intensity={1087.028}
          decay={2}
          position={[4.124, 1.775, 0.912]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <pointLight
          name="Point003"
          intensity={1087.028}
          decay={2}
          position={[-0.646, 1.741, 0.857]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <pointLight
          name="Point004"
          intensity={1087.028}
          decay={2}
          position={[-3.01, 1.774, 0.857]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <pointLight
          name="Point005"
          intensity={1087.028}
          decay={2}
          position={[-3.217, 1.784, -2.204]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <pointLight
          name="Point006"
          intensity={1087.028}
          decay={2}
          position={[-1.918, 1.767, -2.204]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <pointLight
          name="Point007"
          intensity={1087.028}
          decay={2}
          position={[-0.667, 1.809, -2.204]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <pointLight
          name="Point008"
          intensity={1087.028}
          decay={2}
          position={[0.436, 1.789, -2.204]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <pointLight
          name="Point009"
          intensity={1087.028}
          decay={2}
          position={[1.719, 1.799, -2.204]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <directionalLight
          name="luna"
          intensity={683}
          decay={2}
          color="#fffcdd"
          position={[7.729, 20.957, 22.246]}
          rotation={[-0.665, 0.823, 0.521]}
          scale={6.189}
        >
          <group position={[0, 0, -1]} />
        </directionalLight>
        <group name="porta001" position={[2.636, 1.001, 2.226]}>
          <mesh
            name="Cube002"
            geometry={nodes.Cube002.geometry}
            material={materials.PORTA}
          />
          <mesh
            name="Cube002_1"
            geometry={nodes.Cube002_1.geometry}
            material={materials["vetro porta"]}
          />
          <mesh
            name="Cube002_2"
            geometry={nodes.Cube002_2.geometry}
            material={materials["MANIGLIA PORTA"]}
          />
        </group>
        <mesh
          name="tetto"
          geometry={nodes.tetto.geometry}
          material={materials.beige}
          position={[-0.948, 7.345, -0.968]}
        >
          <group name="strutt001" position={[2.255, -5.385, -0.885]} />
          <group
            name="Circle021"
            position={[1.31, -4.074, 1.063]}
            rotation={[0, 0, -0.226]}
          >
            <mesh
              name="Circle003"
              geometry={nodes.Circle003.geometry}
              material={materials.beige}
            />
            <mesh
              name="Circle003_1"
              geometry={nodes.Circle003_1.geometry}
              material={materials["vetro luci.001"]}
            />
          </group>
          <mesh
            name="Cube006"
            geometry={nodes.Cube006.geometry}
            material={materials.beige}
            position={[2.693, -4.375, 0]}
          />
          <mesh
            name="Plane051"
            geometry={nodes.Plane051.geometry}
            material={materials["Material.015"]}
            position={[7.186, -5.579, -1.826]}
            rotation={[0, 0, -Math.PI / 2]}
          >
            <mesh
              name="Sphere007"
              geometry={nodes.Sphere007.geometry}
              material={materials["vetro luci.001"]}
              position={[-0.019, -9.455, 0.59]}
              rotation={[0, 0, Math.PI / 2]}
            />
          </mesh>
          <mesh
            name="Text001"
            geometry={nodes.Text001.geometry}
            material={materials["NEON BLU"]}
            position={[9.878, -2.664, 1.75]}
          >
            {/* <mesh
              name="Text_1"
              geometry={nodes.Text_1.geometry}
              material={materials["NEON BLU"]}
              position={[-8.141, -0.983, 2.731]}
            /> */}
          </mesh>
        </mesh>
        <group name="dietro" position={[1.308, 1.959, -1.853]}>
          <mesh
            name="Cube013"
            geometry={nodes.Cube013.geometry}
            material={materials["Material.006"]}
          />
          <mesh
            name="Cube013_1"
            geometry={nodes.Cube013_1.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            name="Cube013_2"
            geometry={nodes.Cube013_2.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            name="Cube013_3"
            geometry={nodes.Cube013_3.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            name="Cube013_4"
            geometry={nodes.Cube013_4.geometry}
            material={materials.DIETRO}
          />
          <mesh
            name="Cube013_5"
            geometry={nodes.Cube013_5.geometry}
            material={materials.FUORI}
          />
          <mesh
            name="Plane001"
            geometry={nodes.Plane001.geometry}
            material={materials["Material.011"]}
            position={[0, -1.959, 0]}
          />
          <group name="strutt">
            <mesh
              name="Cube001"
              geometry={nodes.Cube001.geometry}
              material={materials["Material.019"]}
            />
            <mesh
              name="Cube001_1"
              geometry={nodes.Cube001_1.geometry}
              material={materials.PAVIMENTO}
            />
            <mesh
              name="Cube001_2"
              geometry={nodes.Cube001_2.geometry}
              material={materials.FUORI}
            />
            <mesh
              name="Cube001_3"
              geometry={nodes.Cube001_3.geometry}
              material={materials["Material.013"]}
            />
            <mesh
              name="Cube001_4"
              geometry={nodes.Cube001_4.geometry}
              material={materials["met battiscopa"]}
            />
            <group name="BezierCurve005" position={[2.902, 0.716, -2.312]}>
              <mesh
                name="BezierCurve005_1"
                geometry={nodes.BezierCurve005_1.geometry}
                material={materials["Material.045"]}
              />
              <mesh
                name="BezierCurve005_2"
                geometry={nodes.BezierCurve005_2.geometry}
                material={materials["Material.001"]}
              />
              <mesh
                name="BezierCurve001"
                geometry={nodes.BezierCurve001.geometry}
                material={materials.traphy}
                position={[-0.233, -0.314, 0.123]}
              />
              <mesh
                name="BezierCurve002"
                geometry={nodes.BezierCurve002.geometry}
                material={materials.traphy}
                position={[-0.233, -0.246, 0.136]}
              />
              <mesh
                name="BezierCurve003"
                geometry={nodes.BezierCurve003.geometry}
                material={materials.traphy}
                position={[0.028, -0.382, 0.149]}
              />
              <mesh
                name="BezierCurve004"
                geometry={nodes.BezierCurve004.geometry}
                material={materials.traphy}
                position={[0.03, -0.353, 0.156]}
              />
              <mesh
                name="Cylinder148"
                geometry={nodes.Cylinder148.geometry}
                material={materials["Material.032"]}
                position={[-0.45, -0.076, 0.116]}
              />
              <mesh
                name="Plane028"
                geometry={nodes.Plane028.geometry}
                material={materials.traphy}
                position={[-0.45, -0.111, 0.123]}
                rotation={[Math.PI / 2, 0, 0]}
              />
            </group>
            <group name="Circle006" position={[-4.215, 0.391, -2.354]}>
              <mesh
                name="Circle001"
                geometry={nodes.Circle001.geometry}
                material={materials["Material.030"]}
              />
              <mesh
                name="Circle001_1"
                geometry={nodes.Circle001_1.geometry}
                material={materials["Material.031"]}
              />
              <mesh
                name="Circle001_2"
                geometry={nodes.Circle001_2.geometry}
                material={materials["vetro porta"]}
              />
              <mesh
                name="Plane004"
                geometry={nodes.Plane004.geometry}
                material={materials.lanc}
                position={[0, 0, 0.109]}
                rotation={[Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="Plane007"
                  geometry={nodes.Plane007.geometry}
                  material={materials.lanc}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                {/* <mesh
                  name="Plane005_1"
                  geometry={nodes.Plane005_1.geometry}
                  material={materials.lanc}
                  rotation={[-Math.PI / 2, 0, 0]}
                /> */}
              </mesh>
            </group>
            <group name="Circle007" position={[3.841, -0.509, -1.961]}>
              <mesh
                name="Circle002"
                geometry={nodes.Circle002.geometry}
                material={materials["Material.033"]}
              />
              <mesh
                name="Circle002_1"
                geometry={nodes.Circle002_1.geometry}
                material={materials["Material.034"]}
              />
              <mesh
                name="Circle002_2"
                geometry={nodes.Circle002_2.geometry}
                material={materials["NEON BLU.001"]}
              />
              <mesh
                name="Circle002_3"
                geometry={nodes.Circle002_3.geometry}
                material={materials["Material.035"]}
              />
              <mesh
                name="Circle002_4"
                geometry={nodes.Circle002_4.geometry}
                material={materials["Material.036"]}
              />
              <mesh
                name="BezierCurve"
                geometry={nodes.BezierCurve.geometry}
                material={materials["Material.041"]}
                position={[0.105, -0.053, -0.053]}
                rotation={[Math.PI, -0.609, Math.PI]}
              />
              <group name="Circle009" position={[-0.05, -0.072, -0.081]}>
                <mesh
                  name="Circle007_1"
                  geometry={nodes.Circle007_1.geometry}
                  material={materials["Material.039"]}
                />
                <mesh
                  name="Circle007_2"
                  geometry={nodes.Circle007_2.geometry}
                  material={materials["Material.040"]}
                />
              </group>
              <mesh
                name="Plane009_4"
                geometry={nodes.Plane009_4.geometry}
                material={materials.FUORI}
                position={[-0.032, -0.065, 0.054]}
              />
            </group>
            <group name="Cube" position={[-2.611, -1.959, -2.287]}>
              <mesh
                name="Cube016"
                geometry={nodes.Cube016.geometry}
                material={materials["Material.023"]}
              />
              <mesh
                name="Cube016_1"
                geometry={nodes.Cube016_1.geometry}
                material={materials["vetro porta"]}
              />
              <mesh
                name="Cube016_2"
                geometry={nodes.Cube016_2.geometry}
                material={materials["Material.022"]}
              />
              <mesh
                name="Cube016_3"
                geometry={nodes.Cube016_3.geometry}
                material={materials["Material.042"]}
              />
              <group name="Cylinder183" position={[0.21, 0.97, 0.403]}>
                <mesh
                  name="Cylinder015"
                  geometry={nodes.Cylinder015.geometry}
                  material={materials["Material.043"]}
                />
                <mesh
                  name="Cylinder015_1"
                  geometry={nodes.Cylinder015_1.geometry}
                  material={materials["Material.044"]}
                />
              </group>
            </group>
            <mesh
              name="Cube002_3"
              geometry={nodes.Cube002_3.geometry}
              material={materials["Material.012"]}
              position={[0.443, 1.615, 0.005]}
            >
              <group name="Cube011" position={[-0.001, -0.351, 0.119]}>
                <mesh
                  name="Cube012"
                  geometry={nodes.Cube012.geometry}
                  material={materials["NEON ROSSO"]}
                />
                <mesh
                  name="Cube012_1"
                  geometry={nodes.Cube012_1.geometry}
                  material={materials["Material.005"]}
                />
                <mesh
                  name="neon"
                  geometry={nodes.neon.geometry}
                  material={materials["NEON ROSSO.001"]}
                  position={[-2.697, 4.122, 0.778]}
                />
              </group>
            </mesh>
            <mesh
              name="Plane002"
              geometry={nodes.Plane002.geometry}
              material={materials.legno}
              position={[-0.203, -0.065, -2.265]}
            >
              <group name="Cube003" position={[0, 0, -0.065]}>
                <mesh
                  name="Cube024"
                  geometry={nodes.Cube024.geometry}
                  material={materials["Material.016"]}
                />
                <mesh
                  name="Cube024_1"
                  geometry={nodes.Cube024_1.geometry}
                  material={materials["met tav"]}
                />
              </group>
              {/* <mesh
                name="Cube004_1"
                geometry={nodes.Cube004_1.geometry}
                material={materials["NEON ROSSO.002"]}
                position={[0.064, 0.249, -0.021]}
              /> */}
              <mesh
                name="Cube013_6"
                geometry={nodes.Cube013_6.geometry}
                material={materials.metallo}
                position={[0, 0, -0.065]}
              />
            </mesh>
            <group name="Plane008_1" position={[-4.359, -1.959, -0.361]}>
              <mesh
                name="Plane009"
                geometry={nodes.Plane009.geometry}
                material={materials["Material.002"]}
              />
              <mesh
                name="Plane009_1"
                geometry={nodes.Plane009_1.geometry}
                material={materials["met battiscopa"]}
              />
              <mesh
                name="Plane009_2"
                geometry={nodes.Plane009_2.geometry}
                material={materials["Material.017"]}
              />
              <mesh
                name="Plane009_3"
                geometry={nodes.Plane009_3.geometry}
                material={materials["met tav"]}
              />
              <group name="Circle002_5" position={[-0.251, 0.66, 0.353]}>
                <mesh
                  name="Circle004"
                  geometry={nodes.Circle004.geometry}
                  material={materials["Material.018"]}
                />
                <mesh
                  name="Circle004_1"
                  geometry={nodes.Circle004_1.geometry}
                  material={materials["met battiscopa"]}
                />
              </group>
              <group name="Cylinder001_2" position={[0.1, 0, 3.67]}>
                <mesh
                  name="Cylinder078"
                  geometry={nodes.Cylinder078.geometry}
                  material={materials["Material.020"]}
                />
                <mesh
                  name="Cylinder078_1"
                  geometry={nodes.Cylinder078_1.geometry}
                  material={materials["Material.021"]}
                />
                <mesh
                  name="Cylinder078_2"
                  geometry={nodes.Cylinder078_2.geometry}
                  material={materials["met tav"]}
                />
              </group>
              {/* <mesh
                name="Plane030_1"
                geometry={nodes.Plane030_1.geometry}
                material={materials["met tav"]}
                position={[0.083, 0.561, 3.116]}
                rotation={[0, 1.571, 0]}
              /> */}
              <group
                name="Plane036"
                position={[0.707, 0.894, -0.123]}
                rotation={[0, 0.1, 0]}
              >
                <mesh
                  name="Plane007_1"
                  geometry={nodes.Plane007_1.geometry}
                  material={materials["Material.037"]}
                />
                <mesh
                  name="Plane007_2"
                  geometry={nodes.Plane007_2.geometry}
                  material={materials["Material.038"]}
                />
              </group>
            </group>
            <mesh
              name="Plane019"
              geometry={nodes.Plane019.geometry}
              material={materials.legno}
              position={[3.146, 0.605, -2.358]}
            />
            <group name="porta004" position={[-4.219, -1.209, -2.367]}>
              <mesh
                name="Cube018"
                geometry={nodes.Cube018.geometry}
                material={materials.PORTA}
              />
              <mesh
                name="Cube018_1"
                geometry={nodes.Cube018_1.geometry}
                material={materials["vetro porta"]}
              />
              <mesh
                name="Cube018_2"
                geometry={nodes.Cube018_2.geometry}
                material={materials["MANIGLIA PORTA"]}
              />
            </group>
          </group>
          <mesh
            name="vetro"
            geometry={nodes.vetro.geometry}
            material={materials["vetro porta"]}
            position={[0, 0, -0.042]}
          />
        </group>
        <mesh
          name="Plane003"
          geometry={nodes.Plane003.geometry}
          material={materials["Material.003"]}
          position={[-1.728, 0, 1.348]}
        >
          <group name="Cylinder149" position={[-6.688, 0, -8.963]}>
            <mesh
              name="Cylinder001"
              geometry={nodes.Cylinder001.geometry}
              material={materials["Material.047"]}
            />
            <mesh
              name="Cylinder001_1"
              geometry={nodes.Cylinder001_1.geometry}
              material={materials["Material.046"]}
            />
          </group>
          <mesh
            name="Plane"
            geometry={nodes.Plane.geometry}
            material={materials.erb}
            position={[-36.966, 0, 7.148]}
          >
            <mesh
              name="0alb"
              geometry={nodes["0alb"].geometry}
              material={materials.alb}
              position={[48.345, 0, -22.547]}
            />
          </mesh>
          <group name="Plane049" position={[-11.5, 0, -13.226]}>
            <mesh
              name="Plane032"
              geometry={nodes.Plane032.geometry}
              material={materials["Material.049"]}
            />
            <mesh
              name="Plane032_1"
              geometry={nodes.Plane032_1.geometry}
              material={materials["Material.050"]}
            />
          </group>
        </mesh>
        <group name="porta002" position={[0.887, 0.75, 2.224]}>
          <mesh
            name="Cube010"
            geometry={nodes.Cube010.geometry}
            material={materials.PORTA}
          />
          <mesh
            name="Cube010_1"
            geometry={nodes.Cube010_1.geometry}
            material={materials["vetro porta"]}
          />
          <mesh
            name="Cube010_2"
            geometry={nodes.Cube010_2.geometry}
            material={materials["MANIGLIA PORTA"]}
          />
        </group>
        <group
          name="tv"
          position={[5.742, 2.791, -4.186]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            name="Plane003_1"
            geometry={nodes.Plane003_1.geometry}
            material={materials.schermo}
          />
          <mesh
            name="Plane003_2"
            geometry={nodes.Plane003_2.geometry}
            material={materials["plastica nera lucida"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/neon.glb");
