/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/optim3.glb 
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations, PerspectiveCamera } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model({ scroll, ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/optim3.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => void (actions["Animation"].play().paused = true), []);
  useFrame((state) => {
    actions["Animation"].time = THREE.MathUtils.lerp(
      actions["Animation"].time,
      actions["Animation"].getClip().duration * scroll.current,
      0.5
    );
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <PerspectiveCamera
          name="Camera_ferma"
          makeDefault
          far={1000}
          near={0.1}
          fov={44.096}
          position={[10.199, 1.7, 14.379]}
          rotation={[0, 0.6, 0]}
        />
        <pointLight
          name="Point010"
          intensity={1}
          decay={2}
          color="#0090ff"
          position={[8.41, 4.923, -1.616]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <pointLight
          name="Point011"
          intensity={1}
          decay={2}
          color="#0090ff"
          position={[1.754, 3.442, 2.461]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <group name="strutt" position={[1.308, 1.959, -1.853]}>
          <mesh
            name="Cube001"
            geometry={nodes.Cube001.geometry}
            material={materials["Material.019"]}
          />
          <mesh
            name="Cube001_1"
            geometry={nodes.Cube001_1.geometry}
            material={materials.PAVIMENTO}
          />
          <mesh
            name="Cube001_2"
            geometry={nodes.Cube001_2.geometry}
            material={materials.FUORI}
          />
          <mesh
            name="Cube001_3"
            geometry={nodes.Cube001_3.geometry}
            material={materials["Material.013"]}
          />
          <mesh
            name="Cube001_4"
            geometry={nodes.Cube001_4.geometry}
            material={materials["met battiscopa"]}
          />
          <group name="strutt001" />
          <pointLight
            name="Point"
            intensity={1}
            decay={2}
            position={[5.056, -0.189, 2.717]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <pointLight
            name="Point002_1"
            intensity={1}
            decay={2}
            position={[2.816, -0.185, 2.766]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <pointLight
            name="Point003"
            intensity={1}
            decay={2}
            position={[-1.954, -0.19, 2.71]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <pointLight
            name="Point004"
            intensity={1}
            decay={2}
            position={[-4.317, -0.185, 2.71]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <pointLight
            name="Point005"
            intensity={1}
            decay={2}
            position={[-4.525, -0.175, -0.351]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <pointLight
            name="Point006"
            intensity={1}
            decay={2}
            position={[-3.226, -0.193, -0.351]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <pointLight
            name="Point007"
            intensity={1}
            decay={2}
            position={[-1.975, -0.151, -0.351]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <pointLight
            name="Point008"
            intensity={1}
            decay={2}
            position={[-0.872, -0.17, -0.351]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <pointLight
            name="Point009"
            intensity={1}
            decay={2}
            position={[0.411, -0.161, -0.351]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            name="BezierCurve"
            geometry={nodes.BezierCurve.geometry}
            material={materials["Material.041"]}
            position={[3.946, -0.562, -2.015]}
            rotation={[Math.PI, -0.609, Math.PI]}
          />
          <mesh
            name="BezierCurve001"
            geometry={nodes.BezierCurve001.geometry}
            material={materials.traphy}
            position={[2.669, 0.401, -2.188]}
          />
          <mesh
            name="BezierCurve002"
            geometry={nodes.BezierCurve002.geometry}
            material={materials.traphy}
            position={[2.669, 0.47, -2.176]}
          />
          <mesh
            name="BezierCurve003"
            geometry={nodes.BezierCurve003.geometry}
            material={materials.traphy}
            position={[2.93, 0.333, -2.162]}
          />
          <mesh
            name="BezierCurve004"
            geometry={nodes.BezierCurve004.geometry}
            material={materials.traphy}
            position={[2.932, 0.363, -2.156]}
          />
          <group name="BezierCurve005" position={[2.902, 0.716, -2.312]}>
            <mesh
              name="BezierCurve005_1"
              geometry={nodes.BezierCurve005_1.geometry}
              material={materials["Material.045"]}
            />
            <mesh
              name="BezierCurve005_2"
              geometry={nodes.BezierCurve005_2.geometry}
              material={materials.Material}
            />
          </group>
          <group name="Circle002" position={[-4.61, -1.299, -0.008]}>
            <mesh
              name="Circle004"
              geometry={nodes.Circle004.geometry}
              material={materials["Material.018"]}
            />
            <mesh
              name="Circle004_1"
              geometry={nodes.Circle004_1.geometry}
              material={materials["met battiscopa"]}
            />
          </group>
          <group name="Circle006" position={[-4.215, 0.391, -2.354]}>
            <mesh
              name="Circle001"
              geometry={nodes.Circle001.geometry}
              material={materials["Material.030"]}
            />
            <mesh
              name="Circle001_1"
              geometry={nodes.Circle001_1.geometry}
              material={materials["Material.031"]}
            />
            <mesh
              name="Circle001_2"
              geometry={nodes.Circle001_2.geometry}
              material={materials["vetro porta"]}
            />
          </group>
          <group name="Circle007" position={[3.841, -0.509, -1.961]}>
            <mesh
              name="Circle002_1"
              geometry={nodes.Circle002_1.geometry}
              material={materials["Material.033"]}
            />
            <mesh
              name="Circle002_2"
              geometry={nodes.Circle002_2.geometry}
              material={materials["Material.034"]}
            />
            <mesh
              castShadow
              material-toneMapped={false}
              material-emissiveIntensity={10}
              name="Circle002_3"
              geometry={nodes.Circle002_3.geometry}
              material={materials["NEON BLU.001"]}
            />
            <mesh
              name="Circle002_4"
              geometry={nodes.Circle002_4.geometry}
              material={materials["Material.035"]}
            />
            <mesh
              name="Circle002_5"
              geometry={nodes.Circle002_5.geometry}
              material={materials["Material.036"]}
            />
          </group>
          <group name="Circle009" position={[3.792, -0.581, -2.042]}>
            <mesh
              name="Circle007_1"
              geometry={nodes.Circle007_1.geometry}
              material={materials["Material.039"]}
            />
            <mesh
              name="Circle007_2"
              geometry={nodes.Circle007_2.geometry}
              material={materials["Material.040"]}
            />
          </group>
          <group
            name="Circle021"
            position={[-0.945, 1.311, 1.948]}
            rotation={[0, 0, -0.226]}
          >
            <mesh
              name="Circle003"
              geometry={nodes.Circle003.geometry}
              material={materials.beige}
            />
            <mesh
              name="Circle003_1"
              geometry={nodes.Circle003_1.geometry}
              material={materials["vetro luci.001"]}
            />
          </group>
          <group name="Cube" position={[-2.611, -1.959, -2.287]}>
            <mesh
              name="Cube016"
              geometry={nodes.Cube016.geometry}
              material={materials["Material.023"]}
            />
            <mesh
              name="Cube016_1"
              geometry={nodes.Cube016_1.geometry}
              material={materials["vetro porta"]}
            />
            <mesh
              name="Cube016_2"
              geometry={nodes.Cube016_2.geometry}
              material={materials["Material.022"]}
            />
            <mesh
              name="Cube016_3"
              geometry={nodes.Cube016_3.geometry}
              material={materials["Material.042"]}
            />
          </group>
          <group name="Cube003" position={[-0.203, -0.065, -2.331]}>
            <mesh
              name="Cube024"
              geometry={nodes.Cube024.geometry}
              material={materials["Material.016"]}
            />
            <mesh
              name="Cube024_1"
              geometry={nodes.Cube024_1.geometry}
              material={materials["met tav"]}
            />
          </group>
          <mesh
            name="Cube006"
            geometry={nodes.Cube006.geometry}
            material={materials.beige}
            position={[0.438, 1.01, 0.885]}
          />
          <mesh
            name="Cube013"
            geometry={nodes.Cube013.geometry}
            material={materials.metallo}
            position={[-0.203, -0.065, -2.331]}
          />
          <group name="Cylinder001" position={[-4.259, -1.959, 3.309]}>
            <mesh
              name="Cylinder078"
              geometry={nodes.Cylinder078.geometry}
              material={materials["Material.020"]}
            />
            <mesh
              name="Cylinder078_1"
              geometry={nodes.Cylinder078_1.geometry}
              material={materials["Material.021"]}
            />
            <mesh
              name="Cylinder078_2"
              geometry={nodes.Cylinder078_2.geometry}
              material={materials["met tav"]}
            />
          </group>
          <mesh
            name="Cylinder148"
            geometry={nodes.Cylinder148.geometry}
            material={materials["Material.032"]}
            position={[2.452, 0.64, -2.195]}
          />
          <group name="Cylinder183" position={[-2.401, -0.99, -1.884]}>
            <mesh
              name="Cylinder015"
              geometry={nodes.Cylinder015.geometry}
              material={materials["Material.043"]}
            />
            <mesh
              name="Cylinder015_1"
              geometry={nodes.Cylinder015_1.geometry}
              material={materials["Material.044"]}
            />
          </group>
          <group name="dietro">
            <mesh
              name="Cube013_1"
              geometry={nodes.Cube013_1.geometry}
              material={materials["Material.006"]}
            />
            <mesh
              name="Cube013_2"
              geometry={nodes.Cube013_2.geometry}
              material={materials["Material.008"]}
            />
            <mesh
              name="Cube013_3"
              geometry={nodes.Cube013_3.geometry}
              material={materials["Material.009"]}
            />
            <mesh
              name="Cube013_4"
              geometry={nodes.Cube013_4.geometry}
              material={materials["Material.010"]}
            />
            <mesh
              name="Cube013_5"
              geometry={nodes.Cube013_5.geometry}
              material={materials.DIETRO}
            />
          </group>
          <mesh
            castShadow
            material-toneMapped={false}
            material-emissiveIntensity={10}
            name="logo"
            geometry={nodes.logo.geometry}
            material={materials.NEONBLU}
            position={[-1.308, 1.532, 5.361]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.617}
          />
          <mesh
            castShadow
            material-toneMapped={false}
            material-emissiveIntensity={10}
            name="neon"
            geometry={nodes.neon.geometry}
            material={materials["NEON ROSSO.001"]}
            position={[-2.255, 5.385, 0.902]}
          />
          <mesh
            castShadow
            material-toneMapped={false}
            material-emissiveIntensity={10}
            name="neonrosso"
            geometry={nodes.neonrosso.geometry}
            material={materials.NEONROSSO}
            position={[-0.137, 0.154, -2.3]}
          />
          <mesh
            castShadow
            material-toneMapped={false}
            material-emissiveIntensity={10}
            name="neonrosso1"
            geometry={nodes.neonrosso1.geometry}
            material={materials.NEONROSSO}
            position={[-0.137, -0.147, -2.3]}
          />
          <mesh
            castShadow
            material-toneMapped={false}
            material-emissiveIntensity={10}
            name="neonrosso2"
            geometry={nodes.neonrosso2.geometry}
            material={materials.NEONROSSO}
            position={[-0.137, -0.83, -2.3]}
          />
          <group name="neontetto" position={[0.442, 1.264, 0.124]}>
            <mesh
              castShadow
              material-toneMapped={false}
              material-emissiveIntensity={10}
              name="Cube012"
              geometry={nodes.Cube012.geometry}
              material={materials.NEONROSSO}
            />
            <mesh
              name="Cube012_1"
              geometry={nodes.Cube012_1.geometry}
              material={materials.neonspento}
            />
          </group>
          <mesh
            name="Plane001"
            geometry={nodes.Plane001.geometry}
            material={materials["Material.011"]}
            position={[0, -1.959, 0]}
          />
          <mesh
            name="Plane002"
            geometry={nodes.Plane002.geometry}
            material={materials.legno}
            position={[-0.203, -0.065, -2.265]}
          />
          <group name="Plane008" position={[-4.359, -1.959, -0.361]}>
            <mesh
              name="Plane009_1"
              geometry={nodes.Plane009_1.geometry}
              material={materials["Material.001"]}
            />
            <mesh
              name="Plane009_2"
              geometry={nodes.Plane009_2.geometry}
              material={materials["met battiscopa"]}
            />
            <mesh
              name="Plane009_3"
              geometry={nodes.Plane009_3.geometry}
              material={materials["Material.017"]}
            />
            <mesh
              name="Plane009_4"
              geometry={nodes.Plane009_4.geometry}
              material={materials["met tav"]}
            />
          </group>
          <mesh
            name="Plane009"
            geometry={nodes.Plane009.geometry}
            material={materials.FUORI}
            position={[3.809, -0.574, -1.907]}
          />
          <mesh
            name="Plane019"
            geometry={nodes.Plane019.geometry}
            material={materials.legno}
            position={[3.146, 0.605, -2.358]}
          />
          <mesh
            name="Plane028"
            geometry={nodes.Plane028.geometry}
            material={materials.traphy}
            position={[2.452, 0.605, -2.188]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <group
            name="Plane036"
            position={[-3.652, -1.066, -0.484]}
            rotation={[0, 0.1, 0]}
          >
            <mesh
              name="Plane007"
              geometry={nodes.Plane007.geometry}
              material={materials["Material.037"]}
            />
            <mesh
              name="Plane007_1"
              geometry={nodes.Plane007_1.geometry}
              material={materials["Material.038"]}
            />
          </group>
          <mesh
            name="Plane051"
            geometry={nodes.Plane051.geometry}
            material={materials["Material.015"]}
            position={[4.931, -0.194, -0.941]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <group name="porta004" position={[-4.219, -1.209, -2.367]}>
            <mesh
              name="Cube018"
              geometry={nodes.Cube018.geometry}
              material={materials.PORTA}
            />
            <mesh
              name="Cube018_1"
              geometry={nodes.Cube018_1.geometry}
              material={materials["vetro porta"]}
            />
            <mesh
              name="Cube018_2"
              geometry={nodes.Cube018_2.geometry}
              material={materials["MANIGLIA PORTA"]}
            />
          </group>
          <mesh
            name="Sphere007"
            castShadow
            material-toneMapped={false}
            material-emissiveIntensity={10}
            geometry={nodes.Sphere007.geometry}
            material={materials["vetro luci.001"]}
            position={[-4.525, -0.175, -0.351]}
          />
          <mesh
            name="tavoli"
            geometry={nodes.tavoli.geometry}
            material={materials["met tav"]}
            position={[-4.276, -1.398, 2.755]}
          />
          <mesh
            name="tetto"
            geometry={nodes.tetto.geometry}
            material={materials.beige}
            position={[-2.255, 5.385, 0.885]}
          />
          <mesh
            name="tettoneon"
            geometry={nodes.tettoneon.geometry}
            material={materials["Material.009"]}
            position={[0.453, 1.513, 0.128]}
          />
          <group
            name="tv"
            position={[4.435, 0.832, -2.333]}
            rotation={[Math.PI / 2, 0, 0]}
          >
            <mesh
              name="Plane003_1"
              geometry={nodes.Plane003_1.geometry}
              material={materials.schermo}
            />
            <mesh
              name="Plane003_2"
              geometry={nodes.Plane003_2.geometry}
              material={materials["plastica nera lucida"]}
            />
          </group>
          <mesh
            name="vetro"
            geometry={nodes.vetro.geometry}
            material={materials["vetro porta"]}
            position={[0, 0, -0.042]}
          />
        </group>
        <group name="porta001" position={[2.636, 1.001, 2.226]}>
          <mesh
            name="Cube002"
            geometry={nodes.Cube002.geometry}
            material={materials.PORTA}
          />
          <mesh
            name="Cube002_1"
            geometry={nodes.Cube002_1.geometry}
            material={materials["vetro porta"]}
          />
          <mesh
            name="Cube002_2"
            geometry={nodes.Cube002_2.geometry}
            material={materials["MANIGLIA PORTA"]}
          />
        </group>
        <mesh
          name="Plane003"
          geometry={nodes.Plane003.geometry}
          material={materials["Material.002"]}
          position={[-1.728, 0, 1.348]}
        >
          <directionalLight
            name="luna"
            intensity={1}
            decay={2}
            color="#fffcdd"
            position={[9.457, 20.957, 20.898]}
            rotation={[-0.665, 0.823, 0.521]}
            scale={6.189}
          >
            <group position={[0, 0, -1]} />
          </directionalLight>
          <pointLight
            name="Point001_1"
            intensity={1}
            decay={2}
            position={[7.962, 1.77, -4.144]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            name="0alb"
            geometry={nodes["0alb"].geometry}
            material={materials.alb}
            position={[11.379, 0, -15.399]}
          />
          <group name="Cylinder149" position={[-6.688, 0, -8.963]}>
            <mesh
              name="Cylinder001_1"
              geometry={nodes.Cylinder001_1.geometry}
              material={materials["Material.047"]}
            />
            <mesh
              name="Cylinder001_2"
              geometry={nodes.Cylinder001_2.geometry}
              material={materials["Material.046"]}
            />
          </group>
          <mesh
            name="Plane"
            geometry={nodes.Plane.geometry}
            material={materials.erb}
            position={[-36.966, 0, 7.148]}
          />
          <group name="Plane049" position={[-11.5, 0, -13.226]}>
            <mesh
              name="Plane032"
              geometry={nodes.Plane032.geometry}
              material={materials["Material.049"]}
            />
            <mesh
              name="Plane032_1"
              geometry={nodes.Plane032_1.geometry}
              material={materials["Material.050"]}
            />
          </group>
        </mesh>
        <group name="porta002" position={[0.887, 0.75, 2.224]}>
          <mesh
            name="Cube010"
            geometry={nodes.Cube010.geometry}
            material={materials.PORTA}
          />
          <mesh
            name="Cube010_1"
            geometry={nodes.Cube010_1.geometry}
            material={materials["vetro porta"]}
          />
          <mesh
            name="Cube010_2"
            geometry={nodes.Cube010_2.geometry}
            material={materials["MANIGLIA PORTA"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/optim3.glb");
